name: "Mise init"
description: "Initialise an environment with the repository and Mise"

inputs:
  install-args:
    description: "List of tools to install. If left blank all tooling is installed"
    default: ""
    required: false
  repository:
    description: "The repository's name"
    default: ${{ github.repository }}
  ref:
    description: >
      The branch, tag or SHA to checkout.

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}

    - name: Install Mise
      shell: bash
      run: |
        if [[ "$(uname -s)" =~ ^((((CYGWIN)|(MINGW)).*)|(.*Msys))$ ]]
        then
          echo "Installing Mise with Winget"
          winget install jdx.mise --accept-package-agreements --accept-source-agreements
          bin_paths="$USERPROFILE\AppData\Local\mise\shims"
        else
          echo "Installing Mise with sh"
          curl https://mise.run | sh
          bin_paths="$HOME/.local/share/mise/bin"
        fi

        echo "Adding $bin_paths to \$GITHUB_PATH"
        echo "$bin_paths" >> $GITHUB_PATH

        exec bash

        mise trust --all -q --silent
        mise install -q --silent ${{ inputs.install-args }}

        echo "Exporting Mise env vars"

        readarray -d $'\0' ignored < <(
          mise env --redacted --json | jq -c --raw-output0 '. | keys_unsorted | .[]')

        while read -r -d $'\0' key; read -r -d $'\0' value
        do
          skip=false
          for ignored_key in "${ignored[@]}"
          do
            if [[ "$key" == "$ignored_key" ]]
            then
              skip=true
              break
            fi
          done

          if [[ $skip == false ]]
          then
            echo "Exporting env key: \$$key"
            echo "$key=$value" >> "$GITHUB_ENV"
          else
            echo "Ignoring env key: $key"
          fi
        done < <(mise env --json | jq -c --raw-output0 '. | to_entries | map([.key, .value]) | flatten | .[]')
