name: "Mise init"
description: "Initialise an environment with the repository and Mise"

inputs:
  install-args:
    description: "List of tools to install. If left blank all tooling is installed"
    default: ""
    required: false
  use-local:
    description: "List of specific tool versions to use in the local environment"
    default: ${{ github.repository }}
  repository:
    description: "The repository's name"
    default: ${{ github.repository }}
  ref:
    description: >
      The branch, tag or SHA to checkout.

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        submodules: true

    - name: Install Mise
      uses: jdx/mise-action@be3be2260bc02bc3fbf94c5e2fed8b7964baf074 # v3.4.0
      with:
        install_args: ${{ inputs.install-args }}

    - name: Install version-specific tools
      if: ${{ use-local != '' }}
      shell: bash
      run: mise use --env local ${{ inputs.use-local }}
