name: "Mise init"
description: "Initialise an environment with the repository and Mise"

inputs:
  install-args:
    description: "List of tools to install. If left blank all tooling is installed"
    default: ""
    required: false
  use-local:
    description: "List of specific tool versions to use in the local environment"
    default: ""
  repository:
    description: "The repository's name"
    default: ${{ github.repository }}
  ref:
    description: >
      The branch, tag or SHA to checkout.

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        submodules: true

    - name: Install Mise
      uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
      with:
        install_args: ${{ inputs.install-args }}

    - name: Install version-specific tools
      if: ${{ inputs.use-local != '' }}
      shell: bash
      run: mise use --env local ${{ inputs.use-local }}
