name: "Mise init"
description: "Initialise an environment with the repository and Mise"

inputs:
  install-args:
    description: "List of tools to install. If left blank all tooling is installed"
    default: ""
    required: false
  use-local:
    description: "List of specific tool versions to use in the local environment"
    default: ""
  repository:
    description: "The repository's name"
    default: ${{ github.repository }}
  ref:
    description: >
      The branch, tag or SHA to checkout.

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        submodules: true

    - name: Install Mise
      uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
      with:
        install_args: ${{ inputs.install-args }}

    - name: Install version-specific tools
      if: ${{ inputs.use-local != '' }}
      shell: bash
      run: mise use --env local ${{ inputs.use-local }}
