[tools]
# Languages
python = "3"
# CLI tools
# Black has to be installed from PyPi to support their ARM fallback to pure-python.
"npm:renovate" = "41.135.5"
"pipx:codespell" = "2.4.1"
"pipx:pre-commit-hooks" = "6.0.0"
uv = "0.9.4"
just = "1.43.0"

[settings]
activate_aggressive = true
experimental = true
gpg_verify = true
lockfile = true
not_found_auto_install = false
paranoid = true
plugin_autoupdate_last_check_duration = "0"
go_skip_checksum = true

[settings.python]
compile = false
uv_venv_auto = false
