name: "Handle diff file"
description: "Handle any created diff files"

runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: gogo.patch
        path: |
          artifacts/gogo.patch
          gogo.patch

    - name: Run Just jobs
      shell: bash
      env:
        INSTALL_DEV_DEPS: true
      run: |
        set -eu +o pipefail

        just check-diff-file
