name: "Handle diff file"
description: "Handle any created diff files"

runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: gogo.patch
        path: |
          artifacts/gogo.patch
          gogo.patch

    - name: Run Just jobs
      shell: bash
      env:
        INSTALL_DEV_DEPS: true
      run: |
        set -eu +o pipefail

        just check-diff-file
