name: "Just jobs"
description: "Run a Just job"

inputs:
  task-names:
    description: "Names of the tasks to run"
    required: true
  extra-installs:
    description: "List of extra tools to install alongside Just using mise"
    default: ""
    required: false
  use-local:
    description: "List of specific tool versions to use in the local environment"
    default: ${{ github.repository }}
  repository:
    description: "The repository's name"
    default: ${{ github.repository }}
  ref:
    description: >
      The branch, tag or SHA to checkout.

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        submodules: true

    - name: Install Mise
      uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3.3.1
      with:
        install_args: just ${{ inputs.extra-installs }}

    - name: Install version-specific tools
      if: ${{ use-local != '' }}
      shell: bash
      run: mise use --env local ${{ inputs.use-local }}

    - name: Run Just jobs
      shell: bash
      run: |
        set -eu +o pipefail

        just ${{ inputs.task-names }}
      env:
        SKIP_MISE_INSTALL: true
