name: "Just jobs"
description: "Run a Just job"

inputs:
  task-names:
    description: "Names of the tasks to run"
    required: true
  extra-installs:
    description: "List of extra tools to install alongside Just using mise"
    default: ""
    required: false
  skip-mise-setup:
    description: "Whether to skip installing Mise before running the job"
    default: "false"
    required: false
  repository:
    description: "The repository's name"
    default: ${{ github.repository }}
  ref:
    description: >
      The branch, tag or SHA to checkout.

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        submodules: true

    - name: Install Mise
      shell: bash
      if: ${{ inputs.skip-mise-setup != "false" }}
      run: |
        set -eu +o pipefail

        if [[ "$(uname -s)" =~ ^((((CYGWIN)|(MINGW)).*)|(.*Msys))$ ]]
        then
          echo "Installing Mise with Winget"
          winget install jdx.mise --accept-package-agreements --accept-source-agreements
          bin_paths="$USERPROFILE\AppData\Local\mise\shims"
        else
          echo "Installing Mise with sh"
          curl https://mise.run | sh
          bin_paths="$HOME/.local/share/mise/bin"
        fi

        echo "Adding $bin_paths to \$GITHUB_PATH"
        echo "$bin_paths" >> $GITHUB_PATH

        exec bash

        mise trust --all -q --silent
        mise install just ${{ inputs.extra-installs }}

    - name: Run Just jobs
      shell: bash
      run: |
        set -eu +o pipefail

        just ${{ inputs.task-names }}
