name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    uses: FasterSpeeding/Piped/.github/workflows/lint.yml@590cbb633dcbd5fc145124ad682ada17481d3fef
