name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    uses: FasterSpeeding/Piped/.github/workflows/lint.yml@5a4ad660b34fa197da9164a93df0e8a5482dccd7
