name: Reformat PR code

on:
  pull_request:
    branches:
      - master

jobs:
  reformat:
    uses: FasterSpeeding/Piped/.github/workflows/reformat.yml@a1c6aca923b5573149ceaf81f0a00e2d598ad9ec
    secrets: inherit
