name: Reformat PR code

on:
  pull_request:
    branches:
      - master

jobs:
  reformat:
    uses: FasterSpeeding/Piped/.github/workflows/reformat.yml@5a4ad660b34fa197da9164a93df0e8a5482dccd7
    secrets: inherit
