name: Reformat PR code

on:
  pull_request:
    branches:
      - master

jobs:
  reformat:
    uses: FasterSpeeding/Piped/.github/workflows/reformat.yml@590cbb633dcbd5fc145124ad682ada17481d3fef
    secrets: inherit
